@Library('Jenkins_shared_library')
def gv

pipeline{
  agent any
  tools{
    maven 'maven'
  }
 
  stages{
        stage("init"){
      steps{
        echo 'here'
       script{
         gv = load "MCS1/script.groovy"
       }
        echo 'here end'
            }
                 }
    stage("build jar"){
      steps{
        script{
       buildJar()
        }
            }
                 }
     stage("build image"){
      steps{
        script{
        buildImage '67.205.176.30:8083/java-app:jma-3.0'
        }
            }
                 }
   
    stage("deploy"){
      steps{
        echo 'deployment'
            }
         }
  }
  
}
