@Library('Jenkins_shared_library')
def gv

pipeline{
  agent any
  tools{
    maven 'maven'
  }
 
  stages{
    stage(" increment stage"){
      steps{
        script{
          echo ' increment app version..'
          sh'mvn -f MCS1/pom.xml build-helper:parse-version versions:set \
          -DnewVersion=\\\${parsedVersion.majorVersion}.\\\${parsedVersion.minorVersion}.\\\${parsedVersion.nextIncrementalVersion} \
          versions:commit'
          echo 'befor read'
          def matcher = readFile('MCS1/pom.xml') =~ '<version>(.+)</version>'
           echo 'after read'
          def version = matcher[0][1]
          echo 'after matcher'
          env.IMAGE_NAME="$version-$BUILD_NUMBER"
          echo 'end incre '
        }
      }
    }
        stage("init"){
      steps{

        echo 'here tigger is working hope gama '

       script{
         gv = load "MCS1/script.groovy"
       }
        echo 'here end'
        
            }
                 }
    stage("build jar"){
      steps{
        script{
       buildJar()
        }
            }
                 }
     stage("build image"){
      steps{
        script{
        buildImage "67.205.176.30:8083/java-app:${IMAGE_NAME}"
        dockerLogin()
        dockerPush "67.205.176.30:8083/java-app:${IMAGE_NAME}"
        }
            }
                 }
   
    stage("deploy"){
      steps{
        echo 'deployment'
            }
         }
  }
  
}
